name: NemanTest

on: [push]

jobs:
  newman-tests:
    runs-on: ubuntu-latest
    
    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Postman Collection v2
        uses: addnab/docker-run-action@v3
        with:
          image: postman/newman:latest
          options: -v ${{ github.workspace }}:/etc/newman
          run: |
            newman run "DevOps-Practice.postman_collection.json" --reporters="cli"
          
