name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Run Postman Collection v2
        run: |
          collectionPath="/home/runner/work/Devops-newman/practice1"
          docker run -v $collectionPath:/etc/newman -t postman/newman:latest run ./DevOps-Practice.postman_collection.json --reporters="cli"
